// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "kkt_update",
        constants$14.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "kkt_init",
        constants$14.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("tic"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("tv_sec"),
            JAVA_LONG.withName("tv_nsec")
        ).withName("toc")
    ).withName("timer");
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("tv_sec"),
        JAVA_LONG.withName("tv_nsec")
    ).withName("timespec");
    static final VarHandle const$4 = constants$22.const$3.varHandle(MemoryLayout.PathElement.groupElement("tv_sec"));
    static final VarHandle const$5 = constants$22.const$3.varHandle(MemoryLayout.PathElement.groupElement("tv_nsec"));
}


