// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final VarHandle const$0 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("nitref"));
    static final VarHandle const$1 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("maxit"));
    static final VarHandle const$2 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("verbose"));
    static final VarHandle const$3 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("max_bk_iter"));
    static final VarHandle const$4 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("bk_scale"));
    static final VarHandle const$5 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("centrality"));
}


