// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final VarHandle const$0 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("zkbar"));
    static final VarHandle const$1 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("a"));
    static final VarHandle const$2 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("d1"));
    static final VarHandle const$3 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$4 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("eta"));
    static final VarHandle const$5 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("eta_square"));
}


