// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "tic",
        constants$2.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "toc",
        constants$4.const$1
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_DOUBLE.withName("gamma"),
        JAVA_DOUBLE.withName("delta"),
        JAVA_DOUBLE.withName("eps"),
        JAVA_DOUBLE.withName("feastol"),
        JAVA_DOUBLE.withName("abstol"),
        JAVA_DOUBLE.withName("reltol"),
        JAVA_DOUBLE.withName("feastol_inacc"),
        JAVA_DOUBLE.withName("abstol_inacc"),
        JAVA_DOUBLE.withName("reltol_inacc"),
        JAVA_LONG.withName("nitref"),
        JAVA_LONG.withName("maxit"),
        JAVA_LONG.withName("verbose"),
        JAVA_LONG.withName("max_bk_iter"),
        JAVA_DOUBLE.withName("bk_scale"),
        JAVA_DOUBLE.withName("centrality")
    ).withName("settings");
    static final VarHandle const$3 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("gamma"));
    static final VarHandle const$4 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("delta"));
    static final VarHandle const$5 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("eps"));
}


