// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final VarHandle const$0 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("by"));
    static final VarHandle const$1 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("hz"));
    static final VarHandle const$2 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("sz"));
    static final VarHandle const$3 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("KKT"));
    static final VarHandle const$4 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("info"));
    static final VarHandle const$5 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("stgs"));
}


