// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final VarHandle const$0 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("P"));
    static final VarHandle const$1 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("Pinv"));
    static final VarHandle const$2 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("PK"));
    static final VarHandle const$3 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("Parent"));
    static final VarHandle const$4 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("Sign"));
    static final VarHandle const$5 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("Pattern"));
}


