// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final VarHandle const$0 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dx1"));
    static final VarHandle const$1 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dx2"));
    static final VarHandle const$2 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dy1"));
    static final VarHandle const$3 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dy2"));
    static final VarHandle const$4 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dz1"));
    static final VarHandle const$5 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("dz2"));
}


