// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("jc"));
    static final VarHandle const$1 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("ir"));
    static final VarHandle const$2 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("pr"));
    static final VarHandle const$3 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("n"));
    static final VarHandle const$4 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("m"));
    static final VarHandle const$5 = constants$4.const$5.varHandle(MemoryLayout.PathElement.groupElement("nnz"));
}


