// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_LONG.withName("n"),
        JAVA_LONG.withName("m"),
        JAVA_LONG.withName("p"),
        JAVA_LONG.withName("D"),
        RuntimeHelper.POINTER.withName("x"),
        RuntimeHelper.POINTER.withName("y"),
        RuntimeHelper.POINTER.withName("z"),
        RuntimeHelper.POINTER.withName("s"),
        RuntimeHelper.POINTER.withName("lambda"),
        JAVA_DOUBLE.withName("kap"),
        JAVA_DOUBLE.withName("tau"),
        RuntimeHelper.POINTER.withName("best_x"),
        RuntimeHelper.POINTER.withName("best_y"),
        RuntimeHelper.POINTER.withName("best_z"),
        RuntimeHelper.POINTER.withName("best_s"),
        JAVA_DOUBLE.withName("best_kap"),
        JAVA_DOUBLE.withName("best_tau"),
        JAVA_DOUBLE.withName("best_cx"),
        JAVA_DOUBLE.withName("best_by"),
        JAVA_DOUBLE.withName("best_hz"),
        RuntimeHelper.POINTER.withName("best_info"),
        RuntimeHelper.POINTER.withName("dsaff"),
        RuntimeHelper.POINTER.withName("dzaff"),
        RuntimeHelper.POINTER.withName("W_times_dzaff"),
        RuntimeHelper.POINTER.withName("dsaff_by_W"),
        RuntimeHelper.POINTER.withName("saff"),
        RuntimeHelper.POINTER.withName("zaff"),
        RuntimeHelper.POINTER.withName("C"),
        RuntimeHelper.POINTER.withName("A"),
        RuntimeHelper.POINTER.withName("G"),
        RuntimeHelper.POINTER.withName("c"),
        RuntimeHelper.POINTER.withName("b"),
        RuntimeHelper.POINTER.withName("h"),
        RuntimeHelper.POINTER.withName("AtoK"),
        RuntimeHelper.POINTER.withName("GtoK"),
        RuntimeHelper.POINTER.withName("xequil"),
        RuntimeHelper.POINTER.withName("Aequil"),
        RuntimeHelper.POINTER.withName("Gequil"),
        JAVA_DOUBLE.withName("resx0"),
        JAVA_DOUBLE.withName("resy0"),
        JAVA_DOUBLE.withName("resz0"),
        RuntimeHelper.POINTER.withName("rx"),
        RuntimeHelper.POINTER.withName("ry"),
        RuntimeHelper.POINTER.withName("rz"),
        JAVA_DOUBLE.withName("rt"),
        JAVA_DOUBLE.withName("hresx"),
        JAVA_DOUBLE.withName("hresy"),
        JAVA_DOUBLE.withName("hresz"),
        JAVA_DOUBLE.withName("nx"),
        JAVA_DOUBLE.withName("ny"),
        JAVA_DOUBLE.withName("nz"),
        JAVA_DOUBLE.withName("ns"),
        JAVA_DOUBLE.withName("cx"),
        JAVA_DOUBLE.withName("by"),
        JAVA_DOUBLE.withName("hz"),
        JAVA_DOUBLE.withName("sz"),
        RuntimeHelper.POINTER.withName("KKT"),
        RuntimeHelper.POINTER.withName("info"),
        RuntimeHelper.POINTER.withName("stgs")
    ).withName("pwork");
    static final VarHandle const$1 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("n"));
    static final VarHandle const$2 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("m"));
    static final VarHandle const$3 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("p"));
    static final VarHandle const$4 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("D"));
    static final VarHandle const$5 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("x"));
}


