// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final VarHandle const$0 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("feastol"));
    static final VarHandle const$1 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("abstol"));
    static final VarHandle const$2 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("reltol"));
    static final VarHandle const$3 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("feastol_inacc"));
    static final VarHandle const$4 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("abstol_inacc"));
    static final VarHandle const$5 = constants$23.const$2.varHandle(MemoryLayout.PathElement.groupElement("reltol_inacc"));
}


