// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("lpc"));
    static final VarHandle const$1 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("soc"));
    static final VarHandle const$2 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("nsoc"));
    static final VarHandle const$3 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("expc"));
    static final VarHandle const$4 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("nexc"));
    static final VarHandle const$5 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("fexv"));
}


