// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(3, JAVA_LONG).withName("colstart"),
        MemoryLayout.sequenceLayout(6, JAVA_DOUBLE).withName("v"),
        MemoryLayout.sequenceLayout(3, JAVA_DOUBLE).withName("g")
    ).withName("expcone");
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_DOUBLE
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "evalExpHessian",
        constants$8.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "evalExpGradient",
        constants$8.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "evalBarrierValue",
        constants$8.const$5
    );
}


