// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final VarHandle const$0 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$1 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("v"));
    static final VarHandle const$2 = constants$9.const$4.varHandle(MemoryLayout.PathElement.groupElement("kkt_idx"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_LONG.withName("p"),
        RuntimeHelper.POINTER.withName("skbar"),
        RuntimeHelper.POINTER.withName("zkbar"),
        JAVA_DOUBLE.withName("a"),
        JAVA_DOUBLE.withName("d1"),
        JAVA_DOUBLE.withName("w"),
        JAVA_DOUBLE.withName("eta"),
        JAVA_DOUBLE.withName("eta_square"),
        RuntimeHelper.POINTER.withName("q"),
        RuntimeHelper.POINTER.withName("Didx"),
        JAVA_DOUBLE.withName("u0"),
        JAVA_DOUBLE.withName("u1"),
        JAVA_DOUBLE.withName("v1")
    ).withName("socone");
    static final VarHandle const$4 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("p"));
    static final VarHandle const$5 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("skbar"));
}


