// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final VarHandle const$0 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("hresz"));
    static final VarHandle const$1 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("nx"));
    static final VarHandle const$2 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("ny"));
    static final VarHandle const$3 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("nz"));
    static final VarHandle const$4 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("ns"));
    static final VarHandle const$5 = constants$31.const$0.varHandle(MemoryLayout.PathElement.groupElement("cx"));
}


