// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("PKPt"),
        RuntimeHelper.POINTER.withName("L"),
        RuntimeHelper.POINTER.withName("D"),
        RuntimeHelper.POINTER.withName("work1"),
        RuntimeHelper.POINTER.withName("work2"),
        RuntimeHelper.POINTER.withName("work3"),
        RuntimeHelper.POINTER.withName("work4"),
        RuntimeHelper.POINTER.withName("work5"),
        RuntimeHelper.POINTER.withName("work6"),
        RuntimeHelper.POINTER.withName("RHS1"),
        RuntimeHelper.POINTER.withName("RHS2"),
        RuntimeHelper.POINTER.withName("dx1"),
        RuntimeHelper.POINTER.withName("dx2"),
        RuntimeHelper.POINTER.withName("dy1"),
        RuntimeHelper.POINTER.withName("dy2"),
        RuntimeHelper.POINTER.withName("dz1"),
        RuntimeHelper.POINTER.withName("dz2"),
        RuntimeHelper.POINTER.withName("P"),
        RuntimeHelper.POINTER.withName("Pinv"),
        RuntimeHelper.POINTER.withName("PK"),
        RuntimeHelper.POINTER.withName("Parent"),
        RuntimeHelper.POINTER.withName("Sign"),
        RuntimeHelper.POINTER.withName("Pattern"),
        RuntimeHelper.POINTER.withName("Flag"),
        RuntimeHelper.POINTER.withName("Lnz"),
        JAVA_DOUBLE.withName("delta")
    ).withName("kkt");
    static final VarHandle const$1 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("PKPt"));
    static final VarHandle const$2 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("L"));
    static final VarHandle const$3 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("D"));
    static final VarHandle const$4 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work1"));
    static final VarHandle const$5 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work2"));
}


