// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final VarHandle const$0 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work3"));
    static final VarHandle const$1 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work4"));
    static final VarHandle const$2 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work5"));
    static final VarHandle const$3 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("work6"));
    static final VarHandle const$4 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("RHS1"));
    static final VarHandle const$5 = constants$17.const$0.varHandle(MemoryLayout.PathElement.groupElement("RHS2"));
}


