// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final VarHandle const$0 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("q"));
    static final VarHandle const$1 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("Didx"));
    static final VarHandle const$2 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("u0"));
    static final VarHandle const$3 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("u1"));
    static final VarHandle const$4 = constants$10.const$3.varHandle(MemoryLayout.PathElement.groupElement("v1"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("lpc"),
        RuntimeHelper.POINTER.withName("soc"),
        JAVA_LONG.withName("nsoc"),
        RuntimeHelper.POINTER.withName("expc"),
        JAVA_LONG.withName("nexc"),
        JAVA_LONG.withName("fexv")
    ).withName("cone");
}


