// Generated by jextract

package com.ustermetrics.ecos4j.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct SuiteSparse_config_struct SuiteSparse_config;
 * }
 */
public final class SuiteSparse_config extends SuiteSparse_config_struct {

    // Suppresses default constructor, ensuring non-instantiability.
    private SuiteSparse_config() {}
}


